import type { Id } from './_generated/dataModel'
import type { Doc } from './_generated/dataModel'

type NewProfile = Omit<Doc<'profiles'>, '_id' | '_creationTime'>

// ברירות המחדל של פרופיל חדש — זהות לאלו שהיו ב-AuthProvider מול Supabase
export function emptyProfile(userId: Id<'users'>): NewProfile {
  const now = new Date().toISOString()
  return {
    user_id: userId,
    display_name: '',
    first_name: '',
    last_name: '',
    gender: 'other',
    seeking: 'both',
    date_of_birth: null,
    birth_year: null,
    marital_status: 'single',
    phone_number: '',
    city: '',
    state: '',
    country: 'IL',
    latitude: null,
    longitude: null,
    bio: '',
    occupation: '',
    education: '',
    religious_level: 'masorti',
    shomer_shabbat: false,
    kosher_level: 'none',
    synagogue_attendance: 'monthly',
    community_background: 'mixed',
    hebrew_fluency: 'native',
    aliyah_plan: 'no',
    children_status: 'no_children',
    children_count: 0,
    children_future: '',
    wants_children: null,
    height_cm: null,
    relationship_goal: [],
    seeking_status: [],
    seeking_with_kids: '',
    age_pref_min: 18,
    age_pref_max: 60,
    distance_pref_km: 80,
    residence_intent: [],
    languages: [],
    romantic_vision: [],
    friday_night: [],
    saturday_morning: [],
    hobbies: [],
    open_questions: {},
    flight_mode_active: false,
    flight_mode_city: '',
    flight_mode_lat: null,
    flight_mode_lng: null,
    is_verified: false,
    is_online: true,
    last_seen: now,
    profile_complete: false,
    subscription_tier: 'free',
    boost_active_until: null,
    views_count: 0,
    is_admin: false,
    approval_status: 'pending',
    approval_note: '',
    approved_at: null,
    approved_by: null,
    created_at: now,
    updated_at: now,
  }
}
