import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!
const DEMO_PASSWORD = 'Bashert2024!'

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error('❌ חסרים משתני סביבה: NEXT_PUBLIC_SUPABASE_URL ו-SUPABASE_SERVICE_ROLE_KEY')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
})

interface SeedUser {
  email: string
  first_name: string
  last_name: string
  display_name: string
  gender: 'male' | 'female'
  seeking: 'male' | 'female' | 'both'
  date_of_birth: string
  city: string
  state: string
  country: string
  bio: string
  occupation: string
  education: string
  religious_level: 'hiloni' | 'masorti' | 'dati_light' | 'dati' | 'haredi'
  shomer_shabbat: boolean
  kosher_level: 'none' | 'kosher_home' | 'kosher_out' | 'strict'
  synagogue_attendance: 'never' | 'holidays' | 'monthly' | 'weekly' | 'daily'
  community_background: 'ashkenazi' | 'sephardic' | 'mizrahi' | 'yemenite' | 'mixed' | 'other'
  hebrew_fluency: 'none' | 'basic' | 'conversational' | 'fluent' | 'native'
  aliyah_plan: 'no' | 'considering' | 'planning' | 'already_made'
  children_status: 'no_children' | 'has_children' | 'wants_children' | 'does_not_want' | 'open'
  wants_children: boolean
  height_cm: number
  is_verified: boolean
  subscription_tier: 'free' | 'gold' | 'platinum'
  photos: string[]
}

const users: SeedUser[] = [
  // ===== נשים =====
  {
    email: 'mia.cohen@bashert-demo.com',
    first_name: 'מיה',
    last_name: 'כהן',
    display_name: 'מיה כהן',
    gender: 'female',
    seeking: 'male',
    date_of_birth: '1997-04-12',
    city: 'תל אביב',
    state: '',
    country: 'IL',
    bio: 'אוהבת ים, ספרים טובים וערבים בסיכום השבוע עם חברים. עובדת כמורה לאמנות ומחפשת מישהו שאפשר לצחוק איתו ולשתוק איתו בנוחות. חשוב לי ערכי משפחה ויהדות ברמה שלי – מסורת בבית, חופשיות בחיים.',
    occupation: 'מורה לאמנות',
    education: 'תואר שני, האוניברסיטה הפתוחה',
    religious_level: 'masorti',
    shomer_shabbat: false,
    kosher_level: 'kosher_home',
    synagogue_attendance: 'holidays',
    community_background: 'ashkenazi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 165,
    is_verified: true,
    subscription_tier: 'gold',
    photos: [
      'https://randomuser.me/api/portraits/women/1.jpg',
      'https://randomuser.me/api/portraits/women/11.jpg',
    ],
  },
  {
    email: 'noa.levi@bashert-demo.com',
    first_name: 'נועה',
    last_name: 'לוי',
    display_name: 'נועה לוי',
    gender: 'female',
    seeking: 'male',
    date_of_birth: '1993-08-23',
    city: 'ירושלים',
    state: '',
    country: 'IL',
    bio: 'רופאת משפחה בקופ״ח, אמא גרושה לבת אחת נפלאה (6). חיה לפי לוח הזמנים של הספרים הרפואיים אבל מחפשת מישהו שיזכיר לי שיש חיים גם מחוץ לקליניקה. אני דתיה-לייט, שומרת שבת אבל פתוחה למגוון.',
    occupation: 'רופאת משפחה',
    education: 'M.D., האוניברסיטה העברית',
    religious_level: 'dati_light',
    shomer_shabbat: true,
    kosher_level: 'kosher_out',
    synagogue_attendance: 'monthly',
    community_background: 'mizrahi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'has_children',
    wants_children: true,
    height_cm: 162,
    is_verified: true,
    subscription_tier: 'platinum',
    photos: [
      'https://randomuser.me/api/portraits/women/2.jpg',
      'https://randomuser.me/api/portraits/women/12.jpg',
      'https://randomuser.me/api/portraits/women/22.jpg',
    ],
  },
  {
    email: 'tamar.shapira@bashert-demo.com',
    first_name: 'תמר',
    last_name: 'שפירא',
    display_name: 'תמר שפירא',
    gender: 'female',
    seeking: 'male',
    date_of_birth: '1995-01-30',
    city: 'רעננה',
    state: '',
    country: 'IL',
    bio: 'עורכת דין בהייטק, מתמחה בחוזים ודיני עבודה. בזמן הפנוי – טיולים לחו״ל, בישול טבעוני ופודקאסטים על היסטוריה יהודית. מחפשת גבר שיש לו תשוקה למשהו – לא משנה מה, רק שיאמין בו.',
    occupation: 'עורכת דין',
    education: 'LL.B., אוניברסיטת תל אביב',
    religious_level: 'hiloni',
    shomer_shabbat: false,
    kosher_level: 'none',
    synagogue_attendance: 'holidays',
    community_background: 'ashkenazi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 170,
    is_verified: false,
    subscription_tier: 'free',
    photos: [
      'https://randomuser.me/api/portraits/women/3.jpg',
      'https://randomuser.me/api/portraits/women/13.jpg',
    ],
  },
  {
    email: 'shira.bendavid@bashert-demo.com',
    first_name: 'שירה',
    last_name: 'בן-דוד',
    display_name: 'שירה בן-דוד',
    gender: 'female',
    seeking: 'male',
    date_of_birth: '1998-11-05',
    city: 'חיפה',
    state: '',
    country: 'IL',
    bio: 'מפתחת Full Stack בסטארטאפ ירוק. גדלתי בבית ספרדי-מסורתי וזה חלק ממי שאני – אוכל הבית של אמא, שבת משפחתית, ריקודים בחגים. מחפשת מישהו שיכול לקחת אותי לדייט בקפה ואחר כך לדון על חלומות.',
    occupation: 'מפתחת תוכנה',
    education: 'B.Sc., הטכניון',
    religious_level: 'masorti',
    shomer_shabbat: false,
    kosher_level: 'kosher_home',
    synagogue_attendance: 'holidays',
    community_background: 'sephardic',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 163,
    is_verified: true,
    subscription_tier: 'gold',
    photos: [
      'https://randomuser.me/api/portraits/women/4.jpg',
      'https://randomuser.me/api/portraits/women/14.jpg',
    ],
  },
  {
    email: 'rivka.abramov@bashert-demo.com',
    first_name: 'ריבקה',
    last_name: 'אברמוב',
    display_name: 'ריבקה אברמוב',
    gender: 'female',
    seeking: 'male',
    date_of_birth: '1990-06-18',
    city: 'ירושלים',
    state: '',
    country: 'IL',
    bio: 'עובדת סוציאלית בבית חולים, מתמחה בילדים בסיכון. שומרת שבת ומצוות, אבל עם פתיחות ורוחב לב. המשפחה במרכז חיי – אחיות, אחים, הורים. חלומי הוא בית חם עם מוסיקה ושולחן ערוך לשבת.',
    occupation: 'עובדת סוציאלית',
    education: 'M.S.W., האוניברסיטה העברית',
    religious_level: 'dati',
    shomer_shabbat: true,
    kosher_level: 'strict',
    synagogue_attendance: 'weekly',
    community_background: 'mizrahi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 160,
    is_verified: true,
    subscription_tier: 'free',
    photos: [
      'https://randomuser.me/api/portraits/women/5.jpg',
      'https://randomuser.me/api/portraits/women/15.jpg',
    ],
  },
  {
    email: 'avigail.goldstein@bashert-demo.com',
    first_name: 'אביגיל',
    last_name: 'גולדשטיין',
    display_name: 'אביגיל גולדשטיין',
    gender: 'female',
    seeking: 'male',
    date_of_birth: '1996-03-07',
    city: 'תל אביב',
    state: '',
    country: 'IL',
    bio: 'מעצבת גרפית פרילנסרית, חולה על פופ ארט ואיסוף פוסטרים וינטאג׳. כל סוף שבוע שוק הנמל, כל שני בבוקר ריצה לאורך הטיילת. לא לוקחת את עצמי יותר מדי ברצינות, אבל את מה שחשוב – כן.',
    occupation: 'מעצבת גרפית',
    education: 'B.Des., בצלאל',
    religious_level: 'hiloni',
    shomer_shabbat: false,
    kosher_level: 'none',
    synagogue_attendance: 'holidays',
    community_background: 'ashkenazi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 168,
    is_verified: false,
    subscription_tier: 'free',
    photos: [
      'https://randomuser.me/api/portraits/women/6.jpg',
      'https://randomuser.me/api/portraits/women/16.jpg',
      'https://randomuser.me/api/portraits/women/26.jpg',
    ],
  },
  {
    email: 'yael.friedman@bashert-demo.com',
    first_name: 'יעל',
    last_name: 'פרידמן',
    display_name: 'יעל פרידמן',
    gender: 'female',
    seeking: 'male',
    date_of_birth: '1991-09-14',
    city: 'מודיעין',
    state: '',
    country: 'IL',
    bio: 'רואת חשבון שמגלה שמספרים הם לא הכל. אחרי גירושין לפני שנתיים חזרתי לעצמי – יוגה, ים, חברות טובות. מוכנה לתת לאהבה עוד צ׳אנס עם מישהו בוגר ואמיתי. ילדים – כן, בזמנו.',
    occupation: 'רואת חשבון',
    education: 'B.A. חשבונאות, מכללת הרצוג',
    religious_level: 'dati_light',
    shomer_shabbat: true,
    kosher_level: 'kosher_out',
    synagogue_attendance: 'monthly',
    community_background: 'mixed',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 164,
    is_verified: true,
    subscription_tier: 'gold',
    photos: [
      'https://randomuser.me/api/portraits/women/7.jpg',
      'https://randomuser.me/api/portraits/women/17.jpg',
    ],
  },
  {
    email: 'dana.biton@bashert-demo.com',
    first_name: 'דנה',
    last_name: 'ביטון',
    display_name: 'דנה ביטון',
    gender: 'female',
    seeking: 'male',
    date_of_birth: '1999-12-01',
    city: 'באר שבע',
    state: '',
    country: 'IL',
    bio: 'סטודנטית לסיעוד בשנה ד׳, עובדת במחלקת ילדים. ילידת קריית גת, גדלתי בבית מרוקאי סוחר. אוהבת מוסיקה מזרחית, בישול ים תיכוני ואנשים עם ניצוץ בעיניים. חולמת להתיישב בצפון אחרי הלימודים.',
    occupation: 'סטודנטית לסיעוד',
    education: 'B.Sc. סיעוד, אוניברסיטת בן גוריון',
    religious_level: 'masorti',
    shomer_shabbat: false,
    kosher_level: 'kosher_home',
    synagogue_attendance: 'holidays',
    community_background: 'sephardic',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 161,
    is_verified: false,
    subscription_tier: 'free',
    photos: [
      'https://randomuser.me/api/portraits/women/8.jpg',
      'https://randomuser.me/api/portraits/women/18.jpg',
    ],
  },
  {
    email: 'lee.carmi@bashert-demo.com',
    first_name: 'לי',
    last_name: 'כרמי',
    display_name: 'לי כרמי',
    gender: 'female',
    seeking: 'male',
    date_of_birth: '1994-07-22',
    city: 'הרצליה',
    state: '',
    country: 'IL',
    bio: 'מנהלת שיווק בחברת פינטק, שוחיה מקצועית לשעבר. חיים עם קצב מהיר, אבל יודעת גם לעצור ולהכין ספל קפה ולצפות בשקיעה. מחפשת מישהו שהוא גם חבר הכי טוב וגם הרומן הגדול.',
    occupation: 'מנהלת שיווק',
    education: 'M.B.A., IDC הרצליה',
    religious_level: 'hiloni',
    shomer_shabbat: false,
    kosher_level: 'none',
    synagogue_attendance: 'holidays',
    community_background: 'ashkenazi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 172,
    is_verified: true,
    subscription_tier: 'platinum',
    photos: [
      'https://randomuser.me/api/portraits/women/9.jpg',
      'https://randomuser.me/api/portraits/women/19.jpg',
      'https://randomuser.me/api/portraits/women/29.jpg',
    ],
  },
  {
    email: 'rachel.mizrahi@bashert-demo.com',
    first_name: 'רחל',
    last_name: 'מזרחי',
    display_name: 'רחל מזרחי',
    gender: 'female',
    seeking: 'male',
    date_of_birth: '1988-02-28',
    city: 'תל אביב',
    state: '',
    country: 'IL',
    bio: 'אדריכלית עם משרד קטן ומוצלח בנווה צדק. אחרי 10 שנים של קריירה אני יודעת מה אני רוצה – גם בבניין וגם בחיים. מחפשת גבר בשל שיודע מה הוא רוצה, אוהב לטייל ולא מפחד מרגש.',
    occupation: 'אדריכלית',
    education: 'M.Arch., אוניברסיטת תל אביב',
    religious_level: 'masorti',
    shomer_shabbat: false,
    kosher_level: 'kosher_home',
    synagogue_attendance: 'monthly',
    community_background: 'mizrahi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 167,
    is_verified: true,
    subscription_tier: 'gold',
    photos: [
      'https://randomuser.me/api/portraits/women/10.jpg',
      'https://randomuser.me/api/portraits/women/20.jpg',
    ],
  },

  // ===== גברים =====
  {
    email: 'daniel.avraham@bashert-demo.com',
    first_name: 'דניאל',
    last_name: 'אברהם',
    display_name: 'דניאל אברהם',
    gender: 'male',
    seeking: 'female',
    date_of_birth: '1992-05-16',
    city: 'תל אביב',
    state: '',
    country: 'IL',
    bio: 'מייסד שותף בסטארטאפ CleanTech, אחרי אקזיט קטן ב-2021. גדלתי בבאר שבע בבית לא דתי שהיה מלא ספרים ודיונים שולחניים. מחפש אישה חכמה שמאתגרת אותי מחשבתית ויודעת גם לצחוק.',
    occupation: 'יזם',
    education: 'B.Sc. הנדסת חשמל, הטכניון',
    religious_level: 'masorti',
    shomer_shabbat: false,
    kosher_level: 'kosher_home',
    synagogue_attendance: 'holidays',
    community_background: 'ashkenazi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 182,
    is_verified: true,
    subscription_tier: 'platinum',
    photos: [
      'https://randomuser.me/api/portraits/men/1.jpg',
      'https://randomuser.me/api/portraits/men/11.jpg',
      'https://randomuser.me/api/portraits/men/21.jpg',
    ],
  },
  {
    email: 'yonatan.katz@bashert-demo.com',
    first_name: 'יונתן',
    last_name: 'כץ',
    display_name: 'יונתן כץ',
    gender: 'male',
    seeking: 'female',
    date_of_birth: '1996-10-09',
    city: 'ירושלים',
    state: '',
    country: 'IL',
    bio: 'מהנדס אזרחי שעובד על תשתיות במגזר הציבורי. שומר שבת וחגים, אוהב לנגן גיטרה, לטייל בנגב ולדון בפרשת השבוע עם אנשים פתוחים. מחפש אישה שעולמה היהודי חשוב לה, אבל שאפשר גם לצחוק איתה.',
    occupation: 'מהנדס אזרחי',
    education: 'B.Sc. הנדסה אזרחית, הטכניון',
    religious_level: 'dati_light',
    shomer_shabbat: true,
    kosher_level: 'kosher_out',
    synagogue_attendance: 'weekly',
    community_background: 'ashkenazi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 179,
    is_verified: true,
    subscription_tier: 'gold',
    photos: [
      'https://randomuser.me/api/portraits/men/2.jpg',
      'https://randomuser.me/api/portraits/men/12.jpg',
    ],
  },
  {
    email: 'amit.shalom@bashert-demo.com',
    first_name: 'עמית',
    last_name: 'שלום',
    display_name: 'עמית שלום',
    gender: 'male',
    seeking: 'female',
    date_of_birth: '1989-03-25',
    city: 'חיפה',
    state: '',
    country: 'IL',
    bio: 'מוזיקאי – מנגן בשני להקות, מלמד גיטרה ופסנתר לילדים. גדלתי בבית ספרדי ויש לי אהבה עמוקה לפיוט ולמוסיקה מזרחית. מחפש אישה שאפשר לשתף איתה גם שירים וגם שתיקות.',
    occupation: 'מוזיקאי ומורה למוסיקה',
    education: 'B.Mus, האקדמיה למוסיקה בירושלים',
    religious_level: 'hiloni',
    shomer_shabbat: false,
    kosher_level: 'none',
    synagogue_attendance: 'holidays',
    community_background: 'sephardic',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 176,
    is_verified: false,
    subscription_tier: 'free',
    photos: [
      'https://randomuser.me/api/portraits/men/3.jpg',
      'https://randomuser.me/api/portraits/men/13.jpg',
    ],
  },
  {
    email: 'elad.benami@bashert-demo.com',
    first_name: 'אלעד',
    last_name: 'בן-עמי',
    display_name: 'אלעד בן-עמי',
    gender: 'male',
    seeking: 'female',
    date_of_birth: '1994-12-03',
    city: 'רעננה',
    state: '',
    country: 'IL',
    bio: 'פיזיותרפיסט ספורטיבי – עובד עם קבוצת כדורגל בליגה א׳. ספורטאי בנפש, אבל לא מהאלה שמדברים על זה כל הזמן. משפחה חמה, חברים טובים, חיים בינוניים שאני אוהב. מחפש את הא׳ שמשלימה את הפאזל.',
    occupation: 'פיזיותרפיסט',
    education: 'B.P.T., אוניברסיטת תל אביב',
    religious_level: 'masorti',
    shomer_shabbat: false,
    kosher_level: 'kosher_home',
    synagogue_attendance: 'holidays',
    community_background: 'mixed',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 184,
    is_verified: true,
    subscription_tier: 'gold',
    photos: [
      'https://randomuser.me/api/portraits/men/4.jpg',
      'https://randomuser.me/api/portraits/men/14.jpg',
      'https://randomuser.me/api/portraits/men/24.jpg',
    ],
  },
  {
    email: 'adi.nahum@bashert-demo.com',
    first_name: 'עדי',
    last_name: 'נחום',
    display_name: 'עדי נחום',
    gender: 'male',
    seeking: 'female',
    date_of_birth: '1997-08-11',
    city: 'תל אביב',
    state: '',
    country: 'IL',
    bio: 'צלם פורטרטים ואירועים, גדלתי בתימן ✈️ ישראל. אוהב לתפוס רגעים שאנשים מפספסים – גם עם המצלמה וגם בחיים. עולם יהודי תימני הוא חלק גדול ממי שאני, כולל הפיוטים, הסגנון, והאורח חיים.',
    occupation: 'צלם',
    education: 'תעודת צילום, בית הספר לאמנות המדיה',
    religious_level: 'hiloni',
    shomer_shabbat: false,
    kosher_level: 'kosher_home',
    synagogue_attendance: 'monthly',
    community_background: 'yemenite',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 175,
    is_verified: false,
    subscription_tier: 'free',
    photos: [
      'https://randomuser.me/api/portraits/men/5.jpg',
      'https://randomuser.me/api/portraits/men/15.jpg',
    ],
  },
  {
    email: 'gil.vardi@bashert-demo.com',
    first_name: 'גיל',
    last_name: 'ורדי',
    display_name: 'גיל ורדי',
    gender: 'male',
    seeking: 'female',
    date_of_birth: '1986-06-29',
    city: 'ירושלים',
    state: '',
    country: 'IL',
    bio: 'מורה בישיבת הסדר, מלמד גמרא ומחשבת ישראל. בשעות הפנאי מטייל, קורא ספרות ישראלית ורץ. מחפש אישה דתייה-לייט ומעלה שמחפשת בית יהודי אמיתי, עם אהבה, צחוק ומסירות.',
    occupation: 'מורה בישיבה',
    education: 'סמיכה להוראה, ישיבת הר עציון',
    religious_level: 'dati',
    shomer_shabbat: true,
    kosher_level: 'strict',
    synagogue_attendance: 'daily',
    community_background: 'ashkenazi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 177,
    is_verified: true,
    subscription_tier: 'free',
    photos: [
      'https://randomuser.me/api/portraits/men/6.jpg',
      'https://randomuser.me/api/portraits/men/16.jpg',
    ],
  },
  {
    email: 'ran.landau@bashert-demo.com',
    first_name: 'רן',
    last_name: 'לנדאו',
    display_name: 'רן לנדאו',
    gender: 'male',
    seeking: 'female',
    date_of_birth: '1995-04-18',
    city: 'מודיעין',
    state: '',
    country: 'IL',
    bio: 'מנהל מוצר בחברת SaaS בינלאומית, עובד מרחוק ברובו. כוס קפה בוקר + פרשנות פוליטית + ריצת בוקר = שגרה מושלמת. מחפש מישהי שיש לה עולם משלה אבל רוצה לבנות עולם משותף.',
    occupation: 'מנהל מוצר',
    education: 'B.Sc. מדעי המחשב, הר הצופים',
    religious_level: 'dati_light',
    shomer_shabbat: true,
    kosher_level: 'kosher_out',
    synagogue_attendance: 'weekly',
    community_background: 'ashkenazi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 180,
    is_verified: true,
    subscription_tier: 'gold',
    photos: [
      'https://randomuser.me/api/portraits/men/7.jpg',
      'https://randomuser.me/api/portraits/men/17.jpg',
      'https://randomuser.me/api/portraits/men/27.jpg',
    ],
  },
  {
    email: 'nir.amir@bashert-demo.com',
    first_name: 'ניר',
    last_name: 'אמיר',
    display_name: 'ניר אמיר',
    gender: 'male',
    seeking: 'female',
    date_of_birth: '1991-01-07',
    city: 'תל אביב',
    state: '',
    country: 'IL',
    bio: 'שף שפתח מסעדה קטנה ואהובה בנווה צדק לפני שלוש שנים. הבישול זה לא רק עבודה – זה שפה. גדלתי בבית ספרדי שם כל אירוע היה אירוע קולינרי. מחפש מישהי שאוכל לבשל בשבילה ולצחוק איתה על גבי השיש.',
    occupation: 'שף ומסעדן',
    education: 'בית ספר לאמנויות הבישול, ניו יורק',
    religious_level: 'masorti',
    shomer_shabbat: false,
    kosher_level: 'kosher_home',
    synagogue_attendance: 'holidays',
    community_background: 'sephardic',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 178,
    is_verified: true,
    subscription_tier: 'platinum',
    photos: [
      'https://randomuser.me/api/portraits/men/8.jpg',
      'https://randomuser.me/api/portraits/men/18.jpg',
    ],
  },
  {
    email: 'uri.shamir@bashert-demo.com',
    first_name: 'אורי',
    last_name: 'שמיר',
    display_name: 'אורי שמיר',
    gender: 'male',
    seeking: 'female',
    date_of_birth: '1998-09-30',
    city: 'הרצליה',
    state: '',
    country: 'IL',
    bio: 'אדריכל צעיר שהחל לעבוד עצמאי, מתמחה בדירות קטנות וחכמות. בן של עולים מניו יורק – לי יש גם אנגלית ואמריקאיות בדם. אוהב ג׳אז, שחייה בים, ועיצוב אינטריאר שמישהו יכול לגור בו.',
    occupation: 'אדריכל',
    education: 'B.Arch., אוניברסיטת תל אביב',
    religious_level: 'hiloni',
    shomer_shabbat: false,
    kosher_level: 'none',
    synagogue_attendance: 'holidays',
    community_background: 'mixed',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'no_children',
    wants_children: true,
    height_cm: 183,
    is_verified: false,
    subscription_tier: 'free',
    photos: [
      'https://randomuser.me/api/portraits/men/9.jpg',
      'https://randomuser.me/api/portraits/men/19.jpg',
    ],
  },
  {
    email: 'matan.aharon@bashert-demo.com',
    first_name: 'מתן',
    last_name: 'אהרון',
    display_name: 'מתן אהרון',
    gender: 'male',
    seeking: 'female',
    date_of_birth: '1984-11-20',
    city: 'באר שבע',
    state: '',
    country: 'IL',
    bio: 'קבלן בנייה בעל חברה משפחתית עם 15 עובדים. אבא גרוש לשלושה ילדים מקסימים (12, 9, 6). יש לי חיים טובים – עבודה שאני אוהב, ילדים שאני מת עליהם, ביתי שרגוע. מחפש אישה שתבין שיש מקום נוסף בחיים האלה.',
    occupation: 'קבלן בנייה',
    education: 'הנדסאי בנייה, ORT',
    religious_level: 'dati_light',
    shomer_shabbat: true,
    kosher_level: 'kosher_out',
    synagogue_attendance: 'weekly',
    community_background: 'mizrahi',
    hebrew_fluency: 'native',
    aliyah_plan: 'already_made',
    children_status: 'has_children',
    wants_children: false,
    height_cm: 181,
    is_verified: true,
    subscription_tier: 'gold',
    photos: [
      'https://randomuser.me/api/portraits/men/10.jpg',
      'https://randomuser.me/api/portraits/men/20.jpg',
      'https://randomuser.me/api/portraits/men/30.jpg',
    ],
  },
]

async function seedProfiles() {
  console.log('🌱 מתחיל ליצור פרופילים...\n')
  let created = 0
  let failed = 0

  for (const u of users) {
    process.stdout.write(`  👤 ${u.display_name}... `)

    // 1. Create auth user
    const { data: authData, error: authError } = await supabase.auth.admin.createUser({
      email: u.email,
      password: DEMO_PASSWORD,
      email_confirm: true,
    })

    if (authError || !authData.user) {
      // Check if already exists
      if (authError?.message?.includes('already')) {
        console.log('⚠️  כבר קיים, מדלג')
      } else {
        console.log(`❌ שגיאה: ${authError?.message}`)
        failed++
      }
      continue
    }

    const userId = authData.user.id

    // 2. Insert profile
    const { error: profileError } = await supabase.from('profiles').insert({
      user_id: userId,
      display_name: u.display_name,
      first_name: u.first_name,
      last_name: u.last_name,
      gender: u.gender,
      seeking: u.seeking,
      date_of_birth: u.date_of_birth,
      city: u.city,
      state: u.state,
      country: u.country,
      bio: u.bio,
      occupation: u.occupation,
      education: u.education,
      religious_level: u.religious_level,
      shomer_shabbat: u.shomer_shabbat,
      kosher_level: u.kosher_level,
      synagogue_attendance: u.synagogue_attendance,
      community_background: u.community_background,
      hebrew_fluency: u.hebrew_fluency,
      aliyah_plan: u.aliyah_plan,
      children_status: u.children_status,
      wants_children: u.wants_children,
      height_cm: u.height_cm,
      is_verified: u.is_verified,
      is_online: Math.random() > 0.6,
      profile_complete: true,
      subscription_tier: u.subscription_tier,
    } as never)

    if (profileError) {
      console.log(`❌ שגיאת פרופיל: ${profileError.message}`)
      failed++
      continue
    }

    // 3. Insert photos
    for (let i = 0; i < u.photos.length; i++) {
      await supabase.from('photos').insert({
        user_id: userId,
        url: u.photos[i],
        thumbnail_url: u.photos[i],
        is_primary: i === 0,
        order_index: i,
      } as never)
    }

    console.log('✅')
    created++

    // Small delay to avoid rate limiting
    await new Promise(r => setTimeout(r, 200))
  }

  console.log(`\n✨ סיום! נוצרו ${created} פרופילים, ${failed} נכשלו.`)
  console.log(`\n🔑 סיסמה לכל הפרופילים: ${DEMO_PASSWORD}`)
}

seedProfiles().catch(console.error)
